[package]
name = "mario-skurt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = { version = "0.10" }
log = { version = "0.4" }
wgpu = { version = "0.16" }
winit = { version = "0.28" }
